spring:
  profiles:
    active: local

springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    use-root-path: true
    
---
spring:
  config:
    activate:
      on-profile: local
  devtools:
    restart:
      enabled: true
server:
  title: sbwbss-local
  port : 8080
  
---
spring:
  config:
    activate:
      on-profile: prod
  devtools:
    restart:
      enabled: true
         
server:
  title: sbwbss-prod
  port : 8081

 